# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - go
    commit-message:
      prefix: deps
      include: scope
    groups:
      golang-x:
        patterns:
          - golang.org/x/*
      prometheus:
        patterns:
          - github.com/prometheus/*
      labstack:
        patterns:
          - github.com/labstack/*

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Kyiv
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: docker
